sequenceDiagram
participant FxA as FxA
participant BA as basket.mozilla.org

FxA-->>FxA: User authenticates
FxA-->>FxA: User opens FxA /settings, clicks Email preferences link
FxA-->>FxA: Generate code for basket using basket's client_id, scope: openid
FxA->>BA: Redirect to basket w/ fake state token, code
Note right of BA: It's not considered <br/> good security to <br/> redirect w/ a fake <br/> state token. Not<br/> too dissimilar to <br/>what we are doing<br>with the basket<br>token today. At<br>least OAuth codes <br>are single use.<br>
BA-->>FxA: Trade code for access_token, id_token
FxA-->>BA: Return access_token, id_token
BA-->>BA: Use info from id_token to open user's email preferences page

