sequenceDiagram
participant UA as Browser Addon
participant FPN as Fx Priv Network Server
participant FxA as FxA Content Server
participant FxAA as FxA Authorization Server
participant FxAP as FxA Profile Server
participant SP as Secure Proxy
participant IN as Internet

UA->>SP: Send network traffic to secure proxy w/ access_token sent in Proxy-Authorization header
SP-->>SP: Verify access token, see access token is expired
SP->>UA: Return an error code indicating access token has expired
UA->>FPN: Request new access token
FPN-->>FPN: Get refresh_token from session info (db, encrypted cookie, etc)
FPN->>FxAA: Use refresh_token, client_secret to fetch access_token w/ `profile` scope
FxAA->>FPN: Return access_token w/ `profile` scope
FPN->>FxAP: Use access_token to fetch profile info
FxAP->>FPN: Return profile info, including subscription info.
FPN-->>FPN: Check if user is allowed to use proxy by looking at subscriptions or lookup in internal DB by uid.
FPN->>FxAA: Using server held client_secret, trade refresh_token to fetch access_token w/ `https://identity.mozilla.com/apps/secure-proxy` scope
FxAA->>FPN: Return access_token w/ `https://identity.mozilla.com/apps/secure-proxy` scope
FPN->>UA: Return bundle w/ access_token for cloudflare, profile info
UA->>SP: Send network traffic to secure proxy w/ access_token sent in Proxy-Authorization header
SP-->>SP: Verify access token, access token is valid
SP->>IN: Forward network traffic
IN->>SP: Return network responses
SP->>UA: Return network responses

